name: Windows-mingw
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
      - '.github/workflows/win-msvc.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/macos.yml'
      - '.github/workflows/win-msvc.yml'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        qt_arch: [mingw64_qt5-gcc, ucrt64_qt5-gcc, mingw32_qt5-gcc, mingw64_qt5-static-gcc, ucrt64_qt5-static-gcc, mingw32_qt5-static-gcc, mingw64_qt5-clang, mingw32_qt5-clang]
        include:
          - qt_arch: mingw64_qt5-gcc
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
          - qt_arch: ucrt64_qt5-gcc
            mingw_arch: UCRT64 
            mingw_prefix: mingw-w64-ucrt-x86_64
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
          - qt_arch: mingw32_qt5-gcc
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
          - qt_arch: mingw64_qt5-static-gcc
            mingw_arch: MINGW64 
            mingw_prefix: mingw-w64-x86_64
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5-static
            qmake: /mingw64/qt5-static/bin/qmake.exe
            windeployqt: ls.exe
          - qt_arch: ucrt64_qt5-static-gcc
            mingw_arch: UCRT64 
            mingw_prefix: mingw-w64-ucrt-x86_64
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5-static
            qmake: /ucrt64/qt5-static/bin/qmake.exe
            windeployqt: ls.exe
          - qt_arch: mingw32_qt5-static-gcc
            mingw_arch: MINGW32
            mingw_prefix: mingw-w64-i686
            toolchains: gcc
            mkspec: win32-g++
            qt_build: qt5-static
            qmake: /mingw32/qt5-static/bin/qmake.exe
            windeployqt: ls.exe
          - qt_arch: mingw64_qt5-clang
            mingw_arch: CLANG64 
            mingw_prefix: mingw-w64-clang-x86_64
            toolchains: clang
            mkspec: win32-clang-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
          - qt_arch: mingw32_qt5-clang
            mingw_arch: CLANG32
            mingw_prefix: mingw-w64-clang-i686
            toolchains: clang
            mkspec: win32-clang-g++
            qt_build: qt5
            qmake: qmake.exe
            windeployqt: windeployqt.exe
    env:
      targetName: corednshome

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.mingw_arch }}
          install:  ${{ matrix.mingw_prefix }}-${{ matrix.toolchains }} ${{ matrix.mingw_prefix }}-make ${{ matrix.mingw_prefix }}-${{ matrix.qt_build }} ${{ matrix.mingw_prefix }}-openssl ${{ matrix.mingw_prefix }}-zstd ${{ matrix.mingw_prefix }}-cmake

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: qmake
        shell: msys2 {0}
        run: |
          bash updatelist.sh
          mkdir build
          cd build
          ${{ matrix.qmake }} -r -spec ${{ matrix.mkspec }} CONFIG+=release CONFIG+=qtquickcompiler ..
          cd ..

      - name: mingw32-make
        shell: msys2 {0}
        run: |
          cd build
          mingw32-make.exe -j `nproc`
          cd ..

      - run: |
          git clone https://github.com/missdeer/mingwdeployqt.git
          
      - name: Build mingwdeployqt
        shell: msys2 {0}
        run: |
          cd mingwdeployqt
          mkdir build
          cd build
          env PATH=$PATH:/${{ matrix.mingw_arch }}/bin cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.c }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} -G Ninja ..
          ninja
          cp mingwdeployqt.exe /${{ matrix.mingw_arch }}/bin/
          cd ../..
          
      - name: deploy
        shell: msys2 {0}
        env:
          archiveName: ${{ env.targetName }}-${{ matrix.toolchains }}
        shell: pwsh
        run: |
          mkdir '${{ env.archiveName }}'
          cp build/src/release/${{ env.targetName }}'.exe' ${{ env.archiveName }}/
          env PATH=$PATH:/${{ matrix.mingw_arch }}/bin /${{ matrix.mingw_arch }}/bin/mingwdeployqt.exe ${{ env.archiveName }}/${{ env.targetName }}'.exe'

      - name: upload artifact
        uses: actions/upload-artifact@v1
        env:
          archiveName: ${{ env.targetName }}-${{ matrix.toolchains }}
        with:
          path: ${{ env.archiveName }}
          name: ${{ env.targetName }}-${{ matrix.mingw_prefix }}-${{ matrix.toolchains }}-${{ matrix.qt_build }}
